sudo: required

services:
  - docker

language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "7"
  - "6"

script:
  - npm install
  - npm run build

cache:
  directories:
    - "node_modules"

after_script:
  - docker build -t tedthedev/crypto-calculator:latest .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push tedthedev/crypto-calculator:latest

deploy:
  skip_cleanup: true

# safelist
branches:
  only:
    - master
    - development